# Generated by Django 3.2.5 on 2021-07-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='amount',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
